### ISSUE TITLE
Get rid of the Makefile and improve dockerfile

### ISSUE THREAD

**Issue by DavidBruant** [anthill/bordeaux3d.ants.builders#8]
https://github.com/anthill/bordeaux3d.ants.builders/blob/master/Makefile is doing only copies of various things.

Dockerfile has all reasons to be at the root. This would remove the need to create a `.tmp` directory.
It's possible to build a docker image from an npm script
https://github.com/DavidBruant/MyWebIntelligence/blob/001932da9d3e7b6d60ed34a9d1985a0c7d9bda34/package.json#L14 (use --file option if necessary)

Use a `.dockerfileignore` to prevent copying to much in the container
https://github.com/DavidBruant/MyWebIntelligence/blob/crawl/.dockerignore
(maybe add `node_modules` in the dockerignore and npm install in the cointainer... well, as it's done today)

dockerfile has lots of `cd bordeaux3d.ants.builders`. Could use `WORKDIR`.

**Comment by vallettea** [comment]
:+1:

**Comment by vallettea** [comment]
I see two down sides: 
1) this works because you don't `npm install` nor `npm build` inside the docker.
2) with -v you give access to a part of the disk whereas with the cp, you have more control of what is in your container and you're sure that an attacker will have access only to this.

**Comment by DavidBruant** [comment]
> 1) this works because you don't npm install nor npm build inside the docker.

Why? It seems like it could be adapted for when you do npm install/build inside the container.

> 2) with -v you give access to a part of the disk whereas with the cp, you have more control of what is in your container and you're sure that an attacker will have access only to this.

Sure, instead of -v and cp, one can use `COPY` in the dockerfile, though (which is equivalent to what the makefile does in number of lines of code, but is part of the dockerfile instead of a separate file). The `.dockerignore` will make critical parts unavailable to the COPY command and the COPY will whitelist what's available in the container.
This needs to be verified, but I think it's possible to make the `.dockerignore` a whitelist and just do `COPY . .` (after a WORKDIR if necessary).

I chose -v, because the code changes a lot and I don't want to have to rebuild every time (the container is aimed at running tests in isolation, not deployment), but the idea can be adapted if the solution requires it.
